<a href="https://colab.research.google.com/github/arumugapandi76/python-learning/blob/main/Pandas_Basics_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd

In [ ]:
bankdata=pd.read_csv("bank-data.csv")

In [ ]:
type(bankdata)

pandas.core.frame.DataFrame

In [ ]:
print(bankdata)

          id  age  gender      region    income married  children  car  \
0    ID12101   48  FEMALE  INNER_CITY  17546.00      NO         1   NO
1    ID12102   40    MALE        TOWN  30085.10     YES         3  YES
2    ID12103   51  FEMALE  INNER_CITY  16575.40     YES         0  YES
3    ID12104   23  FEMALE        TOWN  20375.40     YES         3   NO
4    ID12105   57  FEMALE       RURAL  50576.30     YES         0   NO
..       ...  ...     ...         ...       ...     ...       ...  ...
595  ID12696   61  FEMALE  INNER_CITY  47025.00      NO         2  YES
596  ID12697   30  FEMALE  INNER_CITY   9672.25     YES         0  YES
597  ID12698   31  FEMALE        TOWN  15976.30     YES         0  YES
598  ID12699   29    MALE  INNER_CITY  14711.80     YES         0   NO
599  ID12700   38    MALE        TOWN  26671.60      NO         0  YES

    save_act current_act mortgage  pep
0         NO          NO       NO  YES
1         NO         YES      YES   NO
2        YES         YES       NO   NO
3         NO         YES       NO   NO
4        YES          NO       NO   NO
..       ...         ...      ...  ...
595      YES         YES      YES   NO
596      YES         YES       NO   NO
597      YES          NO       NO  YES
598      YES          NO      YES   NO
599       NO         YES      YES  YES

[600 rows x 12 columns]

In [ ]:
bankdata.head()

,id,age,gender,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,FEMALE,INNER_CITY,17546.0,NO,1,NO,NO,NO,NO,YES
1,ID12102,40,MALE,TOWN,30085.1,YES,3,YES,NO,YES,YES,NO
2,ID12103,51,FEMALE,INNER_CITY,16575.4,YES,0,YES,YES,YES,NO,NO
3,ID12104,23,FEMALE,TOWN,20375.4,YES,3,NO,NO,YES,NO,NO
4,ID12105,57,FEMALE,RURAL,50576.3,YES,0,NO,YES,NO,NO,NO

In [ ]:
bankdata.head(10)

,id,age,gender,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,FEMALE,INNER_CITY,17546.00,NO,1,NO,NO,NO,NO,YES
1,ID12102,40,MALE,TOWN,30085.10,YES,3,YES,NO,YES,YES,NO
2,ID12103,51,FEMALE,INNER_CITY,16575.40,YES,0,YES,YES,YES,NO,NO
3,ID12104,23,FEMALE,TOWN,20375.40,YES,3,NO,NO,YES,NO,NO
4,ID12105,57,FEMALE,RURAL,50576.30,YES,0,NO,YES,NO,NO,NO
5,ID12106,57,FEMALE,TOWN,37869.60,YES,2,NO,YES,YES,NO,YES
6,ID12107,22,MALE,RURAL,8877.07,NO,0,NO,NO,YES,NO,YES
7,ID12108,58,MALE,TOWN,24946.60,YES,0,YES,YES,YES,NO,NO
8,ID12109,37,FEMALE,SUBURBAN,25304.30,YES,2,YES,NO,NO,NO,NO
9,ID12110,54,MALE,TOWN,24212.10,YES,2,YES,YES,YES,NO,NO

In [ ]:
bankdata.tail()

,id,age,gender,region,income,married,children,car,save_act,current_act,mortgage,pep
595,ID12696,61,FEMALE,INNER_CITY,47025.00,NO,2,YES,YES,YES,YES,NO
596,ID12697,30,FEMALE,INNER_CITY,9672.25,YES,0,YES,YES,YES,NO,NO
597,ID12698,31,FEMALE,TOWN,15976.30,YES,0,YES,YES,NO,NO,YES
598,ID12699,29,MALE,INNER_CITY,14711.80,YES,0,NO,YES,NO,YES,NO
599,ID12700,38,MALE,TOWN,26671.60,NO,0,YES,NO,YES,YES,YES

In [ ]:
bankdata.shape

(600, 12)

In [ ]:
bankdata.columns

Index(['id', 'age', 'gender', 'region', 'income', 'married', 'children', 'car',
       'save_act', 'current_act', 'mortgage', 'pep'],
      dtype='object')

In [ ]:
bankdata.age.head(5)

0    48
1    40
2    51
3    23
4    57
Name: age, dtype: int64

In [ ]:
bankdata.describe()

              age        income    children
count  600.000000    600.000000  600.000000
mean    42.395000  27524.031217    1.011667
std     14.424947  12899.468246    1.056752
min     18.000000   5014.210000    0.000000
25%     30.000000  17264.500000    0.000000
50%     42.000000  24925.300000    1.000000
75%     55.250000  36172.675000    2.000000
max     67.000000  63130.100000    3.000000

In [ ]:
bankdata.age.describe()

count    600.000000
mean      42.395000
std       14.424947
min       18.000000
25%       30.000000
50%       42.000000
75%       55.250000
max       67.000000
Name: age, dtype: float64

In [ ]:
bankdata.age.min()

18

In [ ]:
bankdata.gender.value_counts()

gender
FEMALE    300
MALE      300
Name: count, dtype: int64

In [ ]:
bankdata.married.value_counts()

married
YES    396
NO     204
Name: count, dtype: int64

In [ ]:
bankdata.region.value_counts()

region
INNER_CITY    269
TOWN          173
RURAL          96
SUBURBAN       62
Name: count, dtype: int64

In [ ]:
pd.crosstab(bankdata.region,bankdata.gender)

gender      FEMALE  MALE
region
INNER_CITY     131   138
RURAL           47    49
SUBURBAN        30    32
TOWN            92    81

In [ ]:
data1 = bankdata[["id","age","gender","region","income","married"]]
data1.head()

        id  age  gender      region   income married
0  ID12101   48  FEMALE  INNER_CITY  17546.0      NO
1  ID12102   40    MALE        TOWN  30085.1     YES
2  ID12103   51  FEMALE  INNER_CITY  16575.4     YES
3  ID12104   23  FEMALE        TOWN  20375.4     YES
4  ID12105   57  FEMALE       RURAL  50576.3     YES

In [ ]:
bankdata.iloc[3:6,7:9]

  car save_act
3  NO       NO
4  NO      YES
5  NO      YES

In [ ]:
data3=bankdata.iloc[ : ,5:7]
data3.head()

  married  children
0      NO         1
1     YES         3
2     YES         0
3     YES         3
4     YES         0

In [ ]:
bankdata.iloc[: ,[1,4,6]]

     age    income  children
0     48  17546.00         1
1     40  30085.10         3
2     51  16575.40         0
3     23  20375.40         3
4     57  50576.30         0
..   ...       ...       ...
595   61  47025.00         2
596   30   9672.25         0
597   31  15976.30         0
598   29  14711.80         0
599   38  26671.60         0

[600 rows x 3 columns]

In [ ]:
bankdata.iloc[4:6 , :]

,id,age,gender,region,income,married,children,car,save_act,current_act,mortgage,pep
4,ID12105,57,FEMALE,RURAL,50576.3,YES,0,NO,YES,NO,NO,NO
5,ID12106,57,FEMALE,TOWN,37869.6,YES,2,NO,YES,YES,NO,YES

In [ ]:
bankdata.iloc[4:6 , 3:]

  region   income married  children car save_act current_act mortgage  pep
4  RURAL  50576.3     YES         0  NO      YES          NO       NO   NO
5   TOWN  37869.6     YES         2  NO      YES         YES       NO  YES

In [ ]:
bankdata.gender=="FEMALE"

0       True
1      False
2       True
3       True
4       True
       ...
595     True
596     True
597     True
598    False
599    False
Name: gender, Length: 600, dtype: bool

In [ ]:
bankdata[bankdata.gender=="FEMALE"]

,id,age,gender,region,income,married,children,car,save_act,current_act,mortgage,pep
0,ID12101,48,FEMALE,INNER_CITY,17546.00,NO,1,NO,NO,NO,NO,YES
2,ID12103,51,FEMALE,INNER_CITY,16575.40,YES,0,YES,YES,YES,NO,NO
3,ID12104,23,FEMALE,TOWN,20375.40,YES,3,NO,NO,YES,NO,NO
4,ID12105,57,FEMALE,RURAL,50576.30,YES,0,NO,YES,NO,NO,NO
5,ID12106,57,FEMALE,TOWN,37869.60,YES,2,NO,YES,YES,NO,YES
...,...,...,...,...,...,...,...,...,...,...,...,...
591,ID12692,40,FEMALE,INNER_CITY,31473.90,NO,2,NO,YES,YES,YES,YES
594,ID12695,59,FEMALE,RURAL,30971.80,YES,3,YES,YES,YES,YES,NO
595,ID12696,61,FEMALE,INNER_CITY,47025.00,NO,2,YES,YES,YES,YES,NO
596,ID12697,30,FEMALE,INNER_CITY,9672.25,YES,0,YES,YES,YES,NO,NO
597,ID12698,31,FEMALE,TOWN,15976.30,YES,0,YES,YES,NO,NO,YES

In [ ]:
bankdata.shape

(600, 12)

In [ ]:
bankdata["bonus"]= bankdata.income+(bankdata.income*0.1)
bankdata.head()

,id,age,gender,region,income,married,children,car,save_act,current_act,mortgage,pep,bonus
0,ID12101,48,FEMALE,INNER_CITY,17546.0,NO,1,NO,NO,NO,NO,YES,19300.60
1,ID12102,40,MALE,TOWN,30085.1,YES,3,YES,NO,YES,YES,NO,33093.61
2,ID12103,51,FEMALE,INNER_CITY,16575.4,YES,0,YES,YES,YES,NO,NO,18232.94
3,ID12104,23,FEMALE,TOWN,20375.4,YES,3,NO,NO,YES,NO,NO,22412.94
4,ID12105,57,FEMALE,RURAL,50576.3,YES,0,NO,YES,NO,NO,NO,55633.93

In [ ]:
bankdata.shape

(600, 13)

In [ ]:
def agegroup(age):
  if age<=40:
    return "young"
  elif age<60:
    return "middle aged"
  else:
    return "old"

In [ ]:
agegroup(20)

'young'

In [ ]:
bankdata["age_cat"]=bankdata.age.apply(agegroup)
bankdata.head(20)

,id,age,gender,region,income,married,children,car,save_act,current_act,mortgage,pep,bonus,age_cat
0,ID12101,48,FEMALE,INNER_CITY,17546.00,NO,1,NO,NO,NO,NO,YES,19300.600,middle aged
1,ID12102,40,MALE,TOWN,30085.10,YES,3,YES,NO,YES,YES,NO,33093.610,young
2,ID12103,51,FEMALE,INNER_CITY,16575.40,YES,0,YES,YES,YES,NO,NO,18232.940,middle aged
3,ID12104,23,FEMALE,TOWN,20375.40,YES,3,NO,NO,YES,NO,NO,22412.940,young
4,ID12105,57,FEMALE,RURAL,50576.30,YES,0,NO,YES,NO,NO,NO,55633.930,middle aged
5,ID12106,57,FEMALE,TOWN,37869.60,YES,2,NO,YES,YES,NO,YES,41656.560,middle aged
6,ID12107,22,MALE,RURAL,8877.07,NO,0,NO,NO,YES,NO,YES,9764.777,young
7,ID12108,58,MALE,TOWN,24946.60,YES,0,YES,YES,YES,NO,NO,27441.260,middle aged
8,ID12109,37,FEMALE,SUBURBAN,25304.30,YES,2,YES,NO,NO,NO,NO,27834.730,young
9,ID12110,54,MALE,TOWN,24212.10,YES,2,YES,YES,YES,NO,NO,26633.310,middle aged
10,ID12111,66,FEMALE,TOWN,59803.90,YES,0,NO,YES,YES,NO,NO,65784.290,old
11,ID12112,52,FEMALE,INNER_CITY,26658.80,NO,0,YES,YES,YES,YES,NO,29324.680,middle aged
12,ID12113,44,FEMALE,TOWN,15735.80,YES,1,NO,YES,YES,YES,YES,17309.380,middle aged
13,ID12114,66,FEMALE,TOWN,55204.70,YES,1,YES,YES,YES,YES,YES,60725.170,old
14,ID12115,36,MALE,RURAL,19474.60,YES,0,NO,YES,YES,YES,NO,21422.060,young
15,ID12116,38,FEMALE,INNER_CITY,22342.10,YES,0,YES,YES,YES,YES,NO,24576.310,young
16,ID12117,37,FEMALE,TOWN,17729.80,YES,2,NO,NO,NO,YES,NO,19502.780,young
17,ID12118,46,FEMALE,SUBURBAN,41016.00,YES,0,NO,YES,NO,YES,NO,45117.600,middle aged
18,ID12119,62,FEMALE,INNER_CITY,26909.20,YES,0,NO,YES,NO,NO,YES,29600.120,old
19,ID12120,31,MALE,TOWN,22522.80,YES,0,YES,YES,YES,NO,NO,24775.080,young

data export

In [ ]:
bankdata.to_csv("bank_processing.csv",index=False)

In [ ]:
bankdata.to_json("data.json",orient="columns")